---
- name: Playbook to create users using file
  hosts: all
  become: true
  vars_files:
  - users.yml
  tasks:
  - name: create user "{{user2}}"
    user:
      name: "{{user2}}"
      state: present
...
